//go:build linux

package levelzero

import (
	"errors"
	"fmt"
	"sync"
	"unsafe"

	"github.com/ebitengine/purego"
)

// errUnavailable is returned when libze_loader cannot be dlopened.
var errUnavailable = errors.New("level zero loader not installed")

// soNames is the list of shared object names tried in order.
var soNames = []string{"libze_loader.so.1", "libze_loader.so"}

// fnTable holds resolved sysman entry points. Functions are kept as Go
// closures generated by purego.RegisterLibFunc.
type fnTable struct {
	zesInit                         func(uint32) uint32
	zesDriverGet                    func(*uint32, *DriverHandle) uint32
	zesDeviceGet                    func(DriverHandle, *uint32, *DeviceHandle) uint32
	zesDevicePciGetProperties       func(DeviceHandle, *pciProperties) uint32
	zesDeviceEnumPowerDomains       func(DeviceHandle, *uint32, *PwrHandle) uint32
	zesPowerGetProperties           func(PwrHandle, *powerProperties) uint32
	zesPowerGetEnergyCounter        func(PwrHandle, *powerEnergyCounter) uint32
	zesDeviceEnumTemperatureSensors func(DeviceHandle, *uint32, *TempHandle) uint32
	zesTemperatureGetProperties     func(TempHandle, *tempProperties) uint32
	zesTemperatureGetState          func(TempHandle, *float64) uint32
	zesDeviceEnumFrequencyDomains   func(DeviceHandle, *uint32, *FreqHandle) uint32
	zesFrequencyGetProperties       func(FreqHandle, *freqProperties) uint32
	zesFrequencyGetState            func(FreqHandle, *freqState) uint32
	zesFrequencyGetThrottleTime     func(FreqHandle, *freqThrottleTime) uint32
	zesDeviceEnumEngineGroups       func(DeviceHandle, *uint32, *EngineHandle) uint32
	zesEngineGetProperties          func(EngineHandle, *engineProperties) uint32
	zesEngineGetActivity            func(EngineHandle, *engineStats) uint32
	zesDeviceEnumRasErrorSets       func(DeviceHandle, *uint32, *RasHandle) uint32
	zesRasGetProperties             func(RasHandle, *rasProperties) uint32
	zesRasGetState                  func(RasHandle, uint32, *rasState) uint32
	zesDeviceEnumMemoryModules      func(DeviceHandle, *uint32, *MemHandle) uint32
	zesMemoryGetProperties          func(MemHandle, *memProperties) uint32
	zesMemoryGetState               func(MemHandle, *memState) uint32
	zesMemoryGetBandwidth           func(MemHandle, *memBandwidth) uint32
}

var (
	loadOnce  sync.Once
	loadErr   error
	libHandle uintptr
	fns       fnTable
)

// loadLibrary dlopens libze_loader and resolves every needed entry point.
// Failures are sticky — once we conclude the library is missing or broken we
// don't retry.
func loadLibrary() error {
	loadOnce.Do(func() {
		var err error
		var handle uintptr
		for _, name := range soNames {
			handle, err = purego.Dlopen(name, purego.RTLD_NOW|purego.RTLD_GLOBAL)
			if err == nil {
				break
			}
		}
		if err != nil {
			loadErr = fmt.Errorf("%w: %v", errUnavailable, err)
			return
		}
		libHandle = handle

		bind := func(out interface{}, name string) {
			if loadErr != nil {
				return
			}
			defer func() {
				if r := recover(); r != nil {
					loadErr = fmt.Errorf("resolve %s: %v", name, r)
				}
			}()
			purego.RegisterLibFunc(out, handle, name)
		}
		bind(&fns.zesInit, "zesInit")
		bind(&fns.zesDriverGet, "zesDriverGet")
		bind(&fns.zesDeviceGet, "zesDeviceGet")
		bind(&fns.zesDevicePciGetProperties, "zesDevicePciGetProperties")
		bind(&fns.zesDeviceEnumPowerDomains, "zesDeviceEnumPowerDomains")
		bind(&fns.zesPowerGetProperties, "zesPowerGetProperties")
		bind(&fns.zesPowerGetEnergyCounter, "zesPowerGetEnergyCounter")
		bind(&fns.zesDeviceEnumTemperatureSensors, "zesDeviceEnumTemperatureSensors")
		bind(&fns.zesTemperatureGetProperties, "zesTemperatureGetProperties")
		bind(&fns.zesTemperatureGetState, "zesTemperatureGetState")
		bind(&fns.zesDeviceEnumFrequencyDomains, "zesDeviceEnumFrequencyDomains")
		bind(&fns.zesFrequencyGetProperties, "zesFrequencyGetProperties")
		bind(&fns.zesFrequencyGetState, "zesFrequencyGetState")
		bind(&fns.zesFrequencyGetThrottleTime, "zesFrequencyGetThrottleTime")
		bind(&fns.zesDeviceEnumEngineGroups, "zesDeviceEnumEngineGroups")
		bind(&fns.zesEngineGetProperties, "zesEngineGetProperties")
		bind(&fns.zesEngineGetActivity, "zesEngineGetActivity")
		bind(&fns.zesDeviceEnumRasErrorSets, "zesDeviceEnumRasErrorSets")
		bind(&fns.zesRasGetProperties, "zesRasGetProperties")
		bind(&fns.zesRasGetState, "zesRasGetState")
		bind(&fns.zesDeviceEnumMemoryModules, "zesDeviceEnumMemoryModules")
		bind(&fns.zesMemoryGetProperties, "zesMemoryGetProperties")
		bind(&fns.zesMemoryGetState, "zesMemoryGetState")
		bind(&fns.zesMemoryGetBandwidth, "zesMemoryGetBandwidth")
	})
	return loadErr
}

// list runs a (count*, handle*) enumerator twice: once with handle=nil to ask
// the API how many handles exist, then again with a buffer of that size.
func list[T any](enumerator func(*uint32, *T) uint32) ([]T, error) {
	var count uint32
	if rc := enumerator(&count, nil); rc != zeResultSuccess {
		return nil, fmt.Errorf("enumerate count: 0x%x", rc)
	}
	if count == 0 {
		return nil, nil
	}
	out := make([]T, count)
	if rc := enumerator(&count, &out[0]); rc != zeResultSuccess {
		return nil, fmt.Errorf("enumerate fill: 0x%x", rc)
	}
	return out[:count], nil
}

// keep unsafe import alive (used by handle types via package-level type aliases).
var _ = unsafe.Sizeof(uintptr(0))
